<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="LABELHOANCHINH2_files/filelist.xml">
<script src="../inbill/JsBarcode.all.min.js"></script>
<script type="text/javascript" src="../inbill/qrcode.min.js"></script>
<!--[if !mso]>
<style>
v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
x\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style>
<![endif]-->

<style>
@media print {
    .pagebreak { page-break-before: always; } /* page-break-after works, as well */
}

@page {
  size: 100mm 150mm;
  margin: 0;
}

.rotate {
transform: rotate(-90deg);
-moz-transform: rotate(-90deg);
-webkit-transform: rotate(-90deg);
-o-transform: rotate(-90deg);
-ms-transform: rotate(-90deg);
}
</style>

<?php 

	@session_start();

	include("../../conn/db.php");
    @$id = $_GET['id'];
    @$uid = $_SESSION['uid'];
    

?>
<title>BAG CODE <?php echo$package['id_code'];?></title>

<style>
table, th, td {
  border: 1px solid;
}
.icon{
margin-left:-70px;
margin-top:-100px;
height: 150mm;
transform: rotate(90deg);
width: 50mm;
}
</style>
</head>

<body  onload=onReady()>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->



<?php



	 $kienhanga = mysqli_fetch_assoc(mysqli_query($conn,"select * from ksn_shipment_details where id_listhoadon='".$id."' "));

	$laydateshipment = mysqli_fetch_assoc(mysqli_query($conn,"select * from ksn_shipment where id='".$kienhanga['awb']."'"));

		if($laydateshipment['kg_chinhanh'] == "HAN")
	{
		$mabao = '';
	}else if($laydateshipment['kg_chinhanh'] == "DAD")
	{
		$mabao = '';
	}else 
	{
		$mabao = '';
	}
	 $data = mysqli_fetch_assoc(mysqli_query($conn,"SELECT id_code FROM ns_listhoadon WHERE id_code='".$id."'"));

	  
echo'
<div>

<div class="icon"><font size=20px><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$laydateshipment['dest'].'</b></font>
<svg id="barcode'.$data['id_code'].'">
  <path d="M8.578 16.359l4.594-4.594-4.594-4.594 1.406-1.406 6 6-6 6z"></path>
 </svg>
 </div>
</div>
  
	  <input type=hidden id="abcId'.$data['id_code'].'" name="abcName" 
                  value="'.$mabao.'';
				   echo $kienhanga['box_no']; 
				  
				  echo'"/> 
	  

	</div><div style="break-after:page"></div>

				  
<script>
JsBarcode("#barcode'.$data['id_code'].'", document.getElementById(\'abcId'.$data['id_code'].'\').value, {
	
  format: "CODE128",
  lineColor: "",
  width: 2,
  height: 100,
  displayValue: true
});
</script>
';
  
  
  echo'
		<script>
			function onReady()
		{
			
		
';

		$laydulieukienaddz = mysqli_query($conn,"select * from ns_listhoadon where id_package='".$kienhang['id_listhoadon']."'")or die("Loi");

		while($laydulieukienzz = mysqli_fetch_array($laydulieukienaddz,MYSQLI_ASSOC))
		{
	echo'	var qrcode = new QRCode("id_qrcode'.$laydulieukienzz['id_code'].'", {
				text:"https://ksnpost.vn/"+document.getElementById(\'abcId'.$laydulieukienzz['id_code'].'\').value,
				width:120,
				height:115,
				colorDark:"#000000",
				colorLight:"#ffffff",
				correctLevel:QRCode.CorrectLevel.H
			});
	
	';
		}
		
		echo'} </script>';
  
  
?>
<script>
<?php
	if($_GET['print'] == "auto")
	{
		echo'window.addEventListener("load", window.print());
';
	}
	?>
</script>
<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
